export interface Project {
  _id?: string;
  address?: string;
  amenities?: string;
  bedrooms?: string;
  bathrooms?: string;
  basement?: string;
  bylaws?: string;
  city?: string;
  country?: string;
  createdate?: Date;
  construction?: string;
  distancetopublictransport?: string;
  distancetoschoolbus?: string;
  description?: string;
  disclaimer?: string;
  exterior?: string;
  fullbathrooms?: string;
  foundation?: string;
  floorfinish?: string;
  fireplace?: string;
  fireplacefuel?: string;
  features?: string;
  floorplanimage?: string;
  images?: string[];
  landleaseexpiryyear?: string;
  mls?: string;
  maintenancefee?: string;
  maintenancefeeinclusion?: string;
  managementcompany?: string;
  managementcompanyphone?: string;
  name?:string;
  outdoorarea?:string;
  purpose?: string;
  purposelogotype?: string;
  price?: string;
  propertytype?: string;
  propertystyle?: string[];
  parking?: string;
  savedthrough?: string;
  size?: string;
  suite?: string;
  status?: string;
  siteinfluences?: string;
  titleofland?: string;
  themecolor?: string;
  taxes?: string;
  taxesforyear?: string;
  typeofroof?: string;
  userid?: string;
  videoproject?: VideoProject;
  url?: string;
  yearbuilt?: string;
}
export interface VideoProject {
  dimensions?: string;
  instagramposttext?: string;
  music?: string;
  images?: string[];
}
